USE master
GO
CREATE DATABASE QUANLYBANHANG
GO
USE QUANLYBANHANG
GO
CREATE TABLE HANG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TEN NVARCHAR(20),
	SOLUONG INT,
)

CREATE TABLE PHIEUNHAP(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HANG_ID INT,
	SOLUONG INT,
	GIANHAP INT,
	GIAPHANPHOI INT,
	NGAYNHAP DATE,
	FOREIGN KEY (HANG_ID) REFERENCES HANG(ID) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE NGUOIBAN(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TEN NVARCHAR(20),
	SDT NVARCHAR(20),
)
CREATE TABLE NGUOIMUA(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TEN NVARCHAR(20),
	SDT NVARCHAR(20),
	DIACHI NVARCHAR(100)
)
CREATE TABLE BANHANG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NGUOIBAN_ID INT,
	NGUOIMUA_ID INT,
	GIAMGIA INT,
	NGAYBAN DATE,
	TRANGTHAI BIT,
	FOREIGN KEY (NGUOIBAN_ID) REFERENCES NGUOIBAN(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (NGUOIMUA_ID) REFERENCES NGUOIMUA(ID) ON UPDATE CASCADE ON DELETE CASCADE,
)
CREATE TABLE THUTIEN(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BANHANG_ID INT,
	PHUONGTHUCTHANHTOAN NVARCHAR(10),
	SOTIEN INT,
	NGAY DATE
	FOREIGN KEY (BANHANG_ID) REFERENCES BANHANG(ID) ON UPDATE CASCADE ON DELETE CASCADE,
)
CREATE TABLE PHIEUXUAT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HANG_ID INT,
	SOLUONG INT,
	GIABAN INT,
	MABANHANG INT,
	FOREIGN KEY (MABANHANG) REFERENCES BANHANG(ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (HANG_ID) REFERENCES HANG(ID) ON UPDATE CASCADE ON DELETE CASCADE,
)


INSERT INTO HANG VALUES('CAO GOT 85',0)
INSERT INTO HANG VALUES('CAO GOT 95',0)
INSERT INTO HANG VALUES('SUC',0)
INSERT INTO HANG VALUES('BET',0)
INSERT INTO HANG VALUES('THE THAO',0)

INSERT INTO NGUOIBAN VALUES('DIU','0931579336')
INSERT INTO NGUOIBAN VALUES('HONG','0387497685')
INSERT INTO NGUOIBAN VALUES('HUY','0869739322')
INSERT INTO NGUOIBAN VALUES('DUY','0936691365')

INSERT INTO NGUOIMUA VALUES('HAI','0936648442','THAI BINH')
SELECT * FROM NGUOIMUA
SELECT ident_current('NGUOIMUA')
select IDENT_CURRENT(
--## TRIGGER BANG NHAP HANG
ALTER TRIGGER TRG_NHAPHANG_INSERT ON PHIEUNHAP FOR INSERT AS
BEGIN
	DECLARE @HANG_ID INT = (SELECT HANG_ID FROM inserted)
	DECLARE @SOLUONG INT = (SELECT SOLUONG FROM inserted)
	DECLARE @GIANHAP INT = (SELECT GIANHAP FROM inserted)
	DECLARE @GIAPHANPHOI INT = (SELECT GIAPHANPHOI FROM inserted)

	IF (@GIANHAP < 0 OR @GIAPHANPHOI < 0)
		BEGIN
			RAISERROR('GIA KHONG DUOC < 0',16,1)
			ROLLBACK
		END
	ELSE
	BEGIN
		IF @SOLUONG < 0
			BEGIN
				RAISERROR('SO LUONG KHONG DUOC < 0',16,1)
				ROLLBACK
			END
		ELSE
		BEGIN
			UPDATE HANG
			SET SOLUONG = SOLUONG + @SOLUONG
			WHERE HANG.ID = @HANG_ID
		END
	END
END
SELECT * FROM PHIEUNHAP
INSERT INTO PHIEUNHAP  VALUES(1,-100,1,1,GETDATE())
INSERT INTO PHIEUNHAP  VALUES(1,100,-1,0,GETDATE())
INSERT INTO PHIEUNHAP  VALUES(1,100,0,100,GETDATE())

ALTER TRIGGER TRG_NHAPHANG_UPDATE ON PHIEUNHAP FOR UPDATE AS
BEGIN
	DECLARE @SLCU INT = (SELECT SOLUONG FROM deleted)
	DECLARE @SLMOI INT = (SELECT SOLUONG FROM inserted)
	DECLARE @HANG_ID_CU INT = (SELECT HANG_ID FROM deleted)
	DECLARE @HANG_ID_MOI INT = (SELECT HANG_ID FROM inserted)
	DECLARE @HANG_TEN_CU NVARCHAR(20) = (SELECT HANG.TEN FROM HANG WHERE HANG.ID = @HANG_ID_CU)
	DECLARE @GIANHAP INT = (SELECT GIANHAP FROM inserted)
	DECLARE @GIAPHANPHOI INT = (SELECT GIAPHANPHOI FROM inserted)

	IF @GIANHAP < 0 OR @GIAPHANPHOI < 0
		BEGIN
			RAISERROR('GIA KHONG DUOC < 0',16,1)
			ROLLBACK
		END
	ELSE
	BEGIN
		IF @SLMOI < 0
			BEGIN
				RAISERROR('SO LUONG KHONG DUOC < 0',16,1)
				ROLLBACK
			END
		ELSE
			BEGIN
			IF @HANG_ID_CU = @HANG_ID_MOI
				BEGIN
					IF((SELECT SOLUONG - @SLCU + @SLMOI FROM HANG WHERE HANG.ID = @HANG_ID_CU )<0)
						BEGIN
							RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN_CU)
							ROLLBACK
						END
					ELSE
						BEGIN
							UPDATE HANG
							SET SOLUONG = SOLUONG - @SLCU + @SLMOI
							WHERE HANG.ID = @HANG_ID_CU
						END
				END
			ELSE
				BEGIN
					IF((SELECT SOLUONG - @SLCU FROM HANG WHERE HANG.ID = @HANG_ID_CU )<0)
						BEGIN
							RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN_CU)
							ROLLBACK
						END
					ELSE
						BEGIN
							UPDATE HANG
							SET SOLUONG = SOLUONG - @SLCU
							WHERE HANG.ID = @HANG_ID_CU

							UPDATE HANG
							SET SOLUONG = SOLUONG + @SLMOI
							WHERE HANG.ID = @HANG_ID_MOI
						END
				END

			END
	END
END

SELECT * FROM HANG
SELECT * FROM PHIEUNHAP
UPDATE PHIEUNHAP SET SOLUONG = -100 WHERE ID = 1
UPDATE PHIEUNHAP SET GIANHAP = -100 WHERE ID = 1
UPDATE PHIEUNHAP SET GIAPHANPHOI = -100 WHERE ID = 1
UPDATE PHIEUNHAP SET SOLUONG = 50,HANG_ID = 3 WHERE ID = 14

UPDATE HANG SET SOLUONG = 50 WHERE ID = 1
ALTER TRIGGER TRG_NHAPHANG_DELETE ON PHIEUNHAP FOR DELETE AS
BEGIN
	DECLARE @HANG_ID INT = (SELECT HANG_ID FROM deleted)
	DECLARE @HANG_TEN NVARCHAR(20) = (SELECT HANG.TEN FROM HANG WHERE HANG.ID = @HANG_ID)
	IF((SELECT SOLUONG - (SELECT SOLUONG FROM deleted) FROM HANG WHERE HANG.ID = @HANG_ID ) < 0)
	BEGIN
		RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN)
		ROLLBACK
	END
	UPDATE HANG
	SET SOLUONG = SOLUONG - (
		SELECT SOLUONG
		FROM deleted
	)
	WHERE HANG.ID = @HANG_ID
END
 
ENABLE TRIGGER TRG_NHAPHANG_INSERT ON PHIEUNHAP
DISABLE TRIGGER TRG_NHAPHANG_INSERT ON PHIEUNHAP

ENABLE TRIGGER TRG_NHAPHANG_UPDATE ON PHIEUNHAP
DISABLE TRIGGER TRG_NHAPHANG_UPDATE ON PHIEUNHAP

ENABLE TRIGGER TRG_NHAPHANG_DELETE ON PHIEUNHAP
DISABLE TRIGGER TRG_NHAPHANG_DELETE ON PHIEUNHAP

SELECT * FROM HANG
SELECT * FROM PHIEUNHAP
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-13-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-13-2019')

INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-14-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-15-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-16-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-17-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-18-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-19-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-20-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-21-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-22-2019')
INSERT INTO PHIEUNHAP VALUES(1,100,0,0,'12-23-2019')
INSERT INTO PHIEUNHAP VALUES(3,100,0,0,'12-23-2019')
INSERT INTO PHIEUNHAP VALUES(2,100,0,0,'12-23-2019')
SELECT DISTINCT TOP 10 NGAYNHAP FROM PHIEUNHAP ORDER BY NGAYNHAP DESC


--## TRIGGER BANG NHAP HANG

---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------
--## TRIGGER BANG XUAT HANG

ALTER TRIGGER TRG_XUATHANG_INSERT ON PHIEUXUAT FOR INSERT AS
BEGIN
	IF(SELECT GIABAN FROM inserted) < 0 
		BEGIN
			RAISERROR('GIA KHONG DUOC < 0',16,1)
			ROLLBACK
		END
	ELSE
	BEGIN
		DECLARE @HANG_ID_MOI INT = (SELECT HANG_ID FROM inserted)
		DECLARE @HANG_TEN_MOI NVARCHAR(20) = (SELECT HANG.TEN FROM HANG WHERE HANG.ID = @HANG_ID_MOI)
		IF((SELECT SOLUONG - (SELECT SOLUONG FROM inserted) FROM HANG WHERE HANG.ID = (SELECT HANG_ID FROM inserted) ) < 0)
			BEGIN
				RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN_MOI)
				ROLLBACK
			END
		ELSE
			BEGIN
				UPDATE HANG
				SET SOLUONG = SOLUONG - (
					SELECT SOLUONG
					FROM inserted
				)
				WHERE HANG.ID = (
					SELECT HANG_ID
					FROM inserted
				)
			END
	END
END

ALTER TRIGGER TRG_XUATHANG_UPDATE ON PHIEUXUAT FOR UPDATE AS
BEGIN
	IF(SELECT GIABAN FROM inserted) < 0 
		BEGIN
			RAISERROR('GIA KHONG DUOC < 0',16,1)
			ROLLBACK
		END
	ELSE
	BEGIN
		DECLARE @SLCU INT = (SELECT SOLUONG FROM deleted)
		DECLARE @SLMOI INT = (SELECT SOLUONG FROM inserted)
		DECLARE @HANG_ID_CU INT = (SELECT HANG_ID FROM deleted)
		DECLARE @HANG_ID_MOI INT = (SELECT HANG_ID FROM inserted)
		DECLARE @HANG_TEN_CU NVARCHAR(20) = (SELECT HANG.TEN FROM HANG WHERE HANG.ID = @HANG_ID_CU)
		DECLARE @HANG_TEN_MOI NVARCHAR(20) = (SELECT HANG.TEN FROM HANG WHERE HANG.ID = @HANG_ID_MOI)
		IF @HANG_ID_CU = @HANG_ID_MOI
			BEGIN
				IF((SELECT SOLUONG + @SLCU - @SLMOI FROM HANG WHERE HANG.ID = @HANG_ID_CU )<0)
					BEGIN
						RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN_CU)
						ROLLBACK
					END
				ELSE
					BEGIN
						UPDATE HANG
						SET SOLUONG = SOLUONG + @SLCU - @SLMOI
						WHERE HANG.ID = @HANG_ID_CU
					END
			END
		ELSE
			BEGIN
				IF((SELECT SOLUONG - @SLMOI FROM HANG WHERE HANG.ID = @HANG_ID_MOI )<0)
					BEGIN
						RAISERROR('SO LUONG HANG <%s> CO SAN KHONG DU',16,1,@HANG_TEN_MOI)
						ROLLBACK
					END
				ELSE
					BEGIN
						UPDATE HANG
						SET SOLUONG = SOLUONG + @SLCU
						WHERE HANG.ID = @HANG_ID_CU

						UPDATE HANG
						SET SOLUONG = SOLUONG - @SLMOI
						WHERE HANG.ID = @HANG_ID_MOI
					END
			END
	END
END


ALTER TRIGGER TRG_XUATHANG_DELETE ON PHIEUXUAT FOR DELETE AS
BEGIN
	UPDATE HANG
	SET SOLUONG = SOLUONG + (
		SELECT SOLUONG
		FROM deleted
	)
	WHERE HANG.ID = (
		SELECT HANG_ID
		FROM deleted
	)
END

ENABLE TRIGGER TRG_XUATHANG_INSERT ON PHIEUXUAT
DISABLE TRIGGER TRG_XUATHANG_INSERT ON PHIEUXUAT

ENABLE TRIGGER TRG_XUATHANG_UPDATE ON PHIEUXUAT
DISABLE TRIGGER TRG_XUATHANG_UPDATE ON PHIEUXUAT

ENABLE TRIGGER TRG_XUATHANG_DELETE ON PHIEUXUAT
DISABLE TRIGGER TRG_XUATHANG_DELETE ON PHIEUXUAT

SELECT * FROM HANG
SELECT * FROM PHIEUXUAT
INSERT INTO PHIEUXUAT VALUES(1,50,85,85,1)
UPDATE PHIEUXUAT SET SOLUONG = 200,HANG_ID = 1 WHERE PHIEUXUAT.ID = 17 
DELETE FROM PHIEUXUAT WHERE PHIEUXUAT.ID = 15

UPDATE HANG SET SOLUONG = 0 


--## TRIGGER BANG XUAT HANG
---------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM NGUOIMUA WHERE SDT = '0936648442'
SELECT * FROM BANHANG
INSERT INTO BANHANG VALUES(1,1,0,GETDATE(),0)

INSERT INTO THUTIEN VALUES(1,'TIENMAT','8500000',GETDATE())
INSERT INTO PHIEUXUAT VALUES(1,0,100000,1)
SELECT * FROM PHIEUXUAT
SELECT * FROM THUTIEN

SELECT SDT FROM NGUOIBAN WHERE ID = 3
select * from BANHANG
UPDATE BANHANG SET NGUOIBAN_ID = '1',NGUOIMUA_ID = '8',GIAMGIA = '0',TRANGTHAI = '1' WHERE ID = 1
SELECT * FROM THUTIEN
UPDATE THUTIEN SET PHUONGTHUCTHANHTOAN = 'VietinBank',SOTIEN = '0' WHERE BANHANG_ID = '2' AND ID = (SELECT MIN(ID) FROM THUTIEN WHERE BANHANG_ID = '2')
DELETE FROM THUTIEN WHERE THUTIEN.BANHANG_ID = '1'
DELETE top(1)  FROM PHIEUXUAT WHERE MABANHANG = '10'
delete top(1) from THUTIEN where BANHANG_ID = '10'
SELECT BANHANG.ID,NGUOIBAN.ID AS NGUOIBANID,NGUOIBAN.TEN,NGUOIMUA.TEN,NGAYBAN FROM BANHANG 
INNER JOIN NGUOIMUA ON BANHANG.NGUOIMUA_ID = NGUOIMUA.ID 
INNER JOIN NGUOIBAN ON BANHANG.NGUOIBAN_ID = NGUOIBAN.ID
WHERE NGUOIMUA.SDT = '88' AND BANHANG.TRANGTHAI = 0
ORDER BY NGAYBAN desc

SELECT * FROM BANHANG

SELECT HANG.TEN,PHIEUXUAT.SOLUONG FROM PHIEUXUAT INNER JOIN HANG ON PHIEUXUAT.HANG_ID = HANG.ID WHERE PHIEUXUAT.MABANHANG = 4

SELECT NGUOIBAN.ID,NGUOIMUA.SDT,NGUOIMUA.TEN,NGUOIMUA.DIACHI,THUTIEN.PHUONGTHUCTHANHTOAN,THUTIEN.SOTIEN,BANHANG.GIAMGIA,BANHANG.TRANGTHAI
FROM BANHANG
INNER JOIN NGUOIBAN ON BANHANG.NGUOIBAN_ID = NGUOIBAN.ID
INNER JOIN NGUOIMUA ON BANHANG.NGUOIMUA_ID = NGUOIMUA.ID
INNER JOIN THUTIEN ON BANHANG.ID = THUTIEN.BANHANG_ID
WHERE THUTIEN.BANHANG_ID = 11
SELECT * FROM THUTIEN WHERE THUTIEN.BANHANG_ID = 1
SELECT * FROM BANHANG

SELECT HANG_ID,HANG.TEN,PHIEUXUAT.SOLUONG,GIABAN FROM PHIEUXUAT INNER JOIN HANG ON HANG.ID = PHIEUXUAT.HANG_ID WHERE PHIEUXUAT.MABANHANG = 4 AND HANG_ID = 3
SELECT PHIEUXUAT.SOLUONG FROM PHIEUXUAT INNER JOIN HANG ON HANG.ID = PHIEUXUAT.HANG_ID WHERE PHIEUXUAT.MABANHANG = 6 AND HANG_ID = 1


SELECT ident_current('NGUOIMUA')
select * from NGUOIMUA

UPDATE THUTIEN SET PHUONGTHUCTHANHTOAN = 'VietinBank',SOTIEN = '888888' WHERE BANHANG_ID = '13' AND ID = (SELECT MIN(ID) FROM THUTIEN WHERE BANHANG_ID = '13')
INSERT INTO PHIEUXUAT VALUES(5,100,88888,14)
INSERT INTO PHIEUXUAT VALUES(2,100,88888,14)
INSERT INTO PHIEUXUAT VALUES(3,100,88888,14)

select count(*) from THUTIEN where THUTIEN.BANHANG_ID = 13
UPDATE BANHANG SET TRANGTHAI = 0 WHERE ID = 16
SELECT * FROM BANHANG WHERE ID = 16

 select top 10 PHIEUNHAP.ID,HANG.TEN,PHIEUNHAP.SOLUONG,NGAYNHAP,GIANHAP,GIAPHANPHOI from PHIEUNHAP
 INNER JOIN HANG ON HANG.ID = PHIEUNHAP.HANG_ID ORDER BY NGAYNHAP DESC
 SELECT * FROM HANG
 UPDATE PHIEUNHAP SET GIANHAP = '100',GIAPHANPHOI='100' WHERE PHIEUNHAP.ID = '31'

SELECT HANG.TEN,SUM(PHIEUXUAT.SOLUONG) AS SOLUONGBAN,(SELECT SOLUONG FROM HANG WHERE HANG.ID = 1) AS SOLUONGCON,(SELECT SUM(PHIEUXUAT.SOLUONG*PHIEUXUAT.GIABAN) FROM PHIEUXUAT WHERE PHIEUXUAT.HANG_ID = 1) AS SOTIENDABAN,  (SELECT (SELECT SUM(THUTIEN.SOTIEN) FROM THUTIEN INNER JOIN BANHANG ON THUTIEN.BANHANG_ID = BANHANG.ID INNER JOIN PHIEUXUAT ON PHIEUXUAT.MABANHANG = BANHANG.ID WHERE BANHANG.TRANGTHAI = 0 AND PHIEUXUAT.HANG_ID = 1) + (SELECT SUM(PHIEUXUAT.SOLUONG*PHIEUXUAT.GIABAN) FROM PHIEUXUAT INNER JOIN BANHANG ON PHIEUXUAT.MABANHANG = BANHANG.ID WHERE BANHANG.TRANGTHAI = 1 AND PHIEUXUAT.HANG_ID = 1)) AS DOANHTHU FROM PHIEUXUAT
INNER JOIN BANHANG ON BANHANG.ID = PHIEUXUAT.MABANHANG
INNER JOIN HANG ON PHIEUXUAT.HANG_ID = HANG.ID
WHERE MONTH(BANHANG.NGAYBAN) = 12 AND PHIEUXUAT.HANG_ID = 1
GROUP BY PHIEUXUAT.HANG_ID,HANG.TEN
 
 select id from hang
  SELECT * FROM PHIEUXUAT INNER JOIN BANHANG ON BANHANG.ID = PHIEUXUAT.MABANHANG WHERE PHIEUXUAT.HANG_ID = 1
 SELECT HANG.TEN,SUM(PHIEUXUAT.SOLUONG) AS SOLUONGBAN,(SELECT SOLUONG FROM HANG WHERE HANG.ID = 1) AS SOLUONGCON,SUM(PHIEUXUAT.SOLUONG*PHIEUXUAT.GIABAN) AS SOTIENDABAN FROM BANHANG
 INNER JOIN PHIEUXUAT ON BANHANG.ID = PHIEUXUAT.MABANHANG
 INNER JOIN HANG ON PHIEUXUAT.HANG_ID = HANG.ID
 WHERE MONTH(BANHANG.NGAYBAN) = 12 AND PHIEUXUAT.HANG_ID = 1
 GROUP BY HANG.TEN

 SELECT * FROM BANHANG
 INNER JOIN PHIEUXUAT ON BANHANG.ID = PHIEUXUAT.MABANHANG
 INNER JOIN HANG ON PHIEUXUAT.HANG_ID = HANG.ID

 DELETE FROM THUTIEN 
 DELETE TOP(1) FROM PHIEUXUAT
 SELECT * FROM PHIEUXUAT
 DELETE FROM BANHANG
 DELETE TOP(1) FROM PHIEUNHAP
 SELECT * FROM PHIEUNHAP

SELECT * FROM HANG
SELECT * FROM NGUOIBAN
SELECT * FROM NGUOIMUA
SELECT * FROM BANHANG
SELECT * FROM PHIEUNHAP
SELECT * FROM PHIEUXUAT
SELECT * FROM THUTIEN

SELECT BANHANG.ID,NGUOIBAN.TEN,NGUOIMUA.TEN,NGAYBAN FROM BANHANG INNER JOIN NGUOIMUA ON BANHANG.NGUOIMUA_ID = NGUOIMUA.ID INNER JOIN NGUOIBAN ON BANHANG.NGUOIBAN_ID = NGUOIBAN.ID WHERE NGUOIMUA.SDT = '888' AND BANHANG.TRANGTHAI = 0

SELECT * FROM BANHANG

SELECT BANHANG.TRANGTHAI,BANHANG.ID,NGUOIBAN.TEN AS NGUOIBAN,NGUOIMUA.TEN AS KHACH,NGAYBAN,FORMAT(SUM(PHIEUXUAT.GIABAN*PHIEUXUAT.SOLUONG),'#,0') AS TONGTIEN,FORMAT(SUM(BANHANG.GIAMGIA),'#,0') AS GIAMGIA FROM BANHANG INNER JOIN NGUOIMUA ON BANHANG.NGUOIMUA_ID = NGUOIMUA.ID INNER JOIN NGUOIBAN ON BANHANG.NGUOIBAN_ID = NGUOIBAN.ID INNER JOIN PHIEUXUAT ON PHIEUXUAT.MABANHANG = BANHANG.ID LEFT JOIN THUTIEN ON BANHANG.ID = THUTIEN.ID WHERE MONTH(BANHANG.NGAYBAN) = 12 GROUP BY BANHANG.TRANGTHAI,BANHANG.ID,NGUOIBAN.TEN,NGUOIMUA.TEN,NGAYBAN,BANHANG.GIAMGIA ORDER BY NGAYBAN

SELECT FORMAT(SUM(BANHANG.GIAMGIA),'#,0')

;